name: 'ci: build Windows + macOS'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUTF8: '1'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install base build tools
      shell: bash
      run: |
        python -V
        python -m pip install -U pip wheel setuptools
        # Cài luôn PyInstaller + hooks (đừng đợi requirements.txt)
        python -m pip install pyinstaller==6.10.0 pyinstaller-hooks-contrib

    - name: Install project deps
      shell: bash
      run: |
        pip install -r requirements.txt
        # Một số runner báo thiếu openpyxl
        pip install --upgrade openpyxl

    - name: Smoke test imports
      shell: bash
      run: |
        python - <<'PY'
        import sys, platform
        print("Python:", sys.version)
        print("OS:", platform.platform())
        import tkinter, _tkinter, numpy, pandas, loguru
        print("Tk:", tkinter.TkVersion, "| numpy:", numpy.__version__, "| pandas:", pandas.__version__)
        import PyInstaller
        import PyInstaller.__main__
        print("PyInstaller OK")
        PY

    - name: Show PyInstaller version
      shell: bash
      run: |
        python -m PyInstaller --version

    # ===== macOS build =====
    - name: Build on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        rm -rf build dist *.spec || true
        python -m PyInstaller --noconfirm --onefile --windowed ui/app.py \
          --name BlogCommentTool-mac \
          --paths . \
          --add-data "src:src" \
          --add-data "data:data" \
          --hidden-import loguru \
          --hidden-import tkinter --hidden-import _tkinter \
          --collect-submodules tkinter --collect-all loguru \
          --collect-submodules numpy --collect-data numpy \
          --collect-submodules pandas --collect-data pandas \
          --clean --log-level WARN
        # Tạo zip bằng ditto (ổn định trên macOS)
        cd dist && ditto -c -k --sequesterRsrc --keepParent BlogCommentTool-mac BlogCommentTool-mac.zip

    # ===== Windows build =====
    - name: Build on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force build, dist, *.spec -ErrorAction SilentlyContinue
        python -m PyInstaller --noconfirm --onefile --windowed ui/app.py `
          --name BlogCommentTool-win `
          --paths . `
          --add-data "src;src" `
          --add-data "data;data" `
          --hidden-import loguru `
          --hidden-import tkinter --hidden-import _tkinter `
          --collect-submodules tkinter --collect-all loguru `
          --collect-submodules numpy --collect-data numpy `
          --collect-submodules pandas --collect-data pandas `
          --clean --log-level WARN
        Compress-Archive -Path dist\BlogCommentTool-win.exe -DestinationPath dist\BlogCommentTool-win.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: dist/*.zip
        if-no-files-found: error
