name: ci: build win+mac

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt || pip install ^
            numpy==1.26.4 pandas==2.2.2 openpyxl ^
            selenium webdriver-manager loguru typer requests ^
            pyinstaller==6.10.0 pyinstaller-hooks-contrib
        shell: bash

      - name: PyInstaller build
        run: |
          rm -rf build dist *.spec 2>/dev/null || true
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            NAME="BlogCommentTool-win"
          else
            NAME="BlogCommentTool-mac"
          fi
          pyinstaller --noconfirm --onefile --windowed ui/app.py \
            --name "$NAME" \
            --paths . \
            --add-data "src:src" \
            --add-data "data:data" \
            --hidden-import loguru \
            --hidden-import tkinter --hidden-import _tkinter \
            --collect-submodules tkinter --collect-all loguru \
            --collect-submodules numpy --collect-data numpy \
            --collect-submodules pandas --collect-data pandas \
            --clean --log-level WARN
        shell: bash

      - name: Package artifact (zip)
        run: |
          cd dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a BlogCommentTool-win.zip BlogCommentTool-win.exe
          else
            /usr/bin/zip -r BlogCommentTool-mac.zip BlogCommentTool-mac
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }}-build
            path: dist/*.zip
            if-no-files-found: error
